# Generated by Django 3.1.8 on 2022-01-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('c_password', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('RECRUITER', 'Recruiter'), ('ADMIN', 'Admin')], default='Candidate', max_length=10)),
                ('captcha', models.CharField(max_length=15)),
            ],
        ),
    ]
