# Generated by Django 3.1.8 on 2022-01-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='captcha',
        ),
    ]
