# Generated by Django 3.1.8 on 2022-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_signup_c_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
