# Generated by Django 3.1.8 on 2022-01-18 06:56

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_resumefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefile',
            name='resume',
            field=models.FileField(upload_to=""),
        ),
    ]
