# Generated by Django 3.1.8 on 2022-01-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220118_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumefile',
            old_name='resume',
            new_name='file',
        ),
    ]
