# Generated by Django 3.1.8 on 2022-01-19 06:42

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220118_1244'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='resumefile',
            managers=[
                ('empAuth_objects1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
